[brain_met_share, brain_with_intracranial_hemorrhage, brain_tumor_progression][Enhancement] Add premade extracting methods for PhaseIdExtractor
TheLion-ai/UMIE_datasets pull request #100
Opened 2024-11-12 13:23 UTC by bkuchnowski

[Issue link](https://github.com/TheLion-ai/UMIE_datasets/issues/75)

- Simplify PhaseIdExtractors for applicable classes.
- Add BaseExtractor abstract class and move helper functions from BaseStudyIdExtractor to it.
- Make BaseStudyIdExtractor and BasePhaseIdExtractor inherit from it.

2024-11-14 01:11 UTC, andrekomor requested changes

2024-11-14 01:11 UTC, andrekomor commented on src/base/extractors/base_id.py
> +This module contains the definition of the BaseExtractor class.
```suggestion
This module contains the definition of the BaseIdExtractor class.
```

2024-11-14 01:11 UTC, andrekomor commented on src/base/extractors/base_id.py
> +The BaseExtractor class is an abstract base class for extraction of information from image path.
```suggestion
The BaseIdExtractor class is an abstract base class for extraction of information from image path.
```

2024-11-14 01:11 UTC, andrekomor commented on src/base/extractors/base_id.py
> +        node: int = 1,
I think `node` is not a very descriptive variable name. Maybe `ancestor_level` / `parent_level` or something simillar?

2024-11-14 16:14 UTC, bkuchnowski commented on src/base/extractors/base_id.py
> +        Extract the filename without its suffix from a given file path.
I'm using wording from pathlib package which I use here, but it's a fair point that it should be consistent. I propose changing to suffix instead.

2024-11-14 16:18 UTC, bkuchnowski commented on src/base/extractors/base_id.py
> +            basename_only (bool, optional): If True, returns only the base name (stem) of the final directory.
No, I mean if True, you only get name of the folder so `_extract_parent_dir(/home/test1/file.jpg, basename_only=True)` returns `test1` while `_extract_parent_dir(/home/test1/file.jpg, basename_only=False)` returns `/home/test1/`

2024-11-14 16:18 UTC, bkuchnowski commented on src/base/extractors/base_id.py
> +This module contains the definition of the BaseExtractor class.
Good catch.

2024-11-14 16:20 UTC, bkuchnowski commented on src/base/extractors/base_id.py
> +        node: int = 1,
I agree, I think `parent_level` sounds more appropriate

2024-12-08 23:57 UTC, andrekomor commented on src/base/extractors/base_id.py
> +            basename_only (bool, optional): If True, returns only the base name (stem) of the final directory.
Then it would probably be better to call it `include_path`, and change the phrasing in description to `directory name` and `whole directory path`. I think it would just make it easier to use.

2024-12-08 23:57 UTC, andrekomor commented on src/base/extractors/base_id.py
> +        Extract the filename without its suffix from a given file path.
Fine

2024-12-08 23:58 UTC, andrekomor commented on src/base/extractors/base_id.py
> +        node: int = 1,
Fine

2024-12-12 11:58 UTC, bkuchnowski commented on src/base/extractors/base_id.py
> +            basename_only (bool, optional): If True, returns only the base name (stem) of the final directory.
Yeah, I agree, that's definitely better phrasing

2024-12-12 20:17 UTC, andrekomor approved these changes

2024-12-21 18:37 UTC, merged