[Enchance] Add premade extracting methods for imgidextractor
TheLion-ai/UMIE_datasets pull request #87
Opened 2024-08-13 14:48 UTC by KacperKnitter

Issue: #74 

Description:
Add premade extracting methods for ImgIdExtractor.
This pull request introduces image ID extraction methods to the ImgIdExtractor and their usage in inheriting classes, allowing for the unification and reuse of extraction logic across different pipeline classes. Previously, image ID extraction logic was often duplicated across different pipeline classes. This solution centralizes the ID extraction process.

2024-08-14 19:28 UTC, andrekomor requested changes
Please also change tag in title to [Enhancement]

2024-08-14 19:28 UTC, andrekomor commented on src/pipelines/brain_tumor_classification.py
> +        return self._extract_zero()
I think this function should also have a docstring

2024-08-14 19:28 UTC, andrekomor commented on src/base/extractors/img_id.py
> +    def _extract_zero(self) -> str:
I think we should rename it to `_return_zero`, or at least rephrase it in docstring, not to confuse anyone. "Extract" implies, that it will be taken from some input, but the function doesn't accept any arguments, and always returns the same thing.

2024-08-14 19:28 UTC, andrekomor commented on src/base/extractors/img_id.py
> +        """Extract "0.png" as image ID.
```suggestion
        """Return "0.png" as image ID.
```

2024-08-14 19:28 UTC, andrekomor commented on src/base/extractors/img_id.py
> +            str: The extracted image ID.
```suggestion
            str: "0.png".
```

2024-08-14 19:28 UTC, andrekomor commented on src/base/extractors/img_id.py
> +        """Extract last two characters of filename from the path.
Why is function called  `first_two_chars`, and first line of docstring says "Extract last two chars"

2024-08-17 17:21 UTC, KacperKnitter commented on src/base/extractors/img_id.py
> +        """Extract last two characters of filename from the path.
Docstring should say "Extract first two characters", my mistake.

2024-08-26 13:27 UTC, andrekomor approved these changes

2024-08-27 20:58 UTC, merged