[ALL] [Enhancement] Add validate data step
TheLion-ai/UMIE_datasets pull request #90
Opened 2024-08-27 20:39 UTC by A-Huli

Add ValidateData step

- Create a new step for validating UMIE output data at the end of the pipeline
- Add this step as the last step in all of the pipelines
- Fix minor issues for processing entire dataset

2024-08-27 21:08 UTC, andrekomor commented on src/steps/convert_dcm2png.py
> +            os.remove(img_path)
I think this will remove original image from users data storage. I don't think we should do this by default. IMO we shouldn't alter content downloaded by user at all.

2024-08-27 21:08 UTC, andrekomor commented on src/steps/get_file_paths.py
> +                if filename.endswith((".csv", ".json", ".xslx", ".yml", ".txt", ".py", ".md")):
Maybe we should only add supported formats here, and not exclude every other existing format.

2024-08-27 21:08 UTC, andrekomor commented on src/steps/validate_data.py
> +                    print(f"Error in image {obj['umie_path']}: {e}")
Will this except ever get triggered? We do not raise any errors in _validate_object functions.

2024-08-28 10:35 UTC, A-Huli commented on src/steps/convert_dcm2png.py
> +            os.remove(img_path)
Agreed. Removed this line.

2024-08-29 21:45 UTC, andrekomor requested changes

2024-08-29 21:45 UTC, andrekomor commented on src/base/step.py
> +            on_error_remove (bool, optional): If True, remove the image if an error occurs. Defaults to True.
```suggestion
```
This parameter doesn't seem to exist.

2024-08-29 21:45 UTC, andrekomor commented on src/pipelines/coronahack.py
> +    CreateBlankMasks,
Create Blank Masks not in steps. Not even commented

2024-08-29 21:45 UTC, andrekomor commented on src/pipelines/finding_and_measuring_lungs.py
> +from steps.create_blank_masks import CreateBlankMasks
Add to import above

2024-08-29 21:45 UTC, andrekomor commented on src/steps/validate_data.py
Do we expect validation step to interrupt the pipeline, or just print errors?

2024-12-22 21:03 UTC, A-Huli commented on src/steps/validate_data.py
just print errors

2024-12-23 11:51 UTC, AleksanderObuchowski approved these changes
LGTM

2024-12-23 11:57 UTC, merged