[Enhancement] Creates a pipeline for CMMD dataset
TheLion-ai/UMIE_datasets pull request #91
Opened 2024-08-29 22:57 UTC by KacperRogala

**Issue:** #80 

**Description:** 
Creates a preprocessing pipeline for images stored in CMMD dataset. 
The purpose is to add the ability to preprocess another medical image dataset to the repository. The dataset is CMMD (The Chinese Mammography Database) containing 5,202 MG (Mammography) breast images.

Additionally the file steps/convert_dcm2png.py is changed. Previously, for this step to work correctly, the masks_path argument had to be provided in the config/runner_config.py file, even if the dataset did not have masks. Now the masks_path argument is optional.

2024-08-29 23:28 UTC, andrekomor requested changes

2024-08-29 23:28 UTC, andrekomor commented on pyproject.toml
Is this package used anywhere? If no, please restore old poetry files.

2024-08-29 23:28 UTC, andrekomor commented on src/pipelines/cmmd.py
> +        img_id_final = lvl_higher + "_" + img_id
Is `xxxxx` always same length? If so, then I think, we can omit the `+ "_" +` part. Adding another underscore breaks out of our naming convention, by adding another section to the file name, which might be problematic when users try to segregate the files by parsing their names in some way.

2024-08-29 23:28 UTC, andrekomor commented on config/runner_config.py
> +from src.pipelines import (  # CmmdPipeline,
Fix imports. Move cmmd pipeline to import in brackets.

2024-08-29 23:28 UTC, andrekomor commented on README.md
> +  4. Download CMMD_clinicaldata_revision.xlsx from Data Access table (second row) for labels information.
```suggestion
  2. Download .tcia file from Data Access table.
  3. Download [NBIA Data Retriver](https://wiki.cancerimagingarchive.net/display/NBIA/Downloading+TCIA+Images) to be able to download images.
  4. Download CMMD_clinicaldata_revision.xlsx from Data Access table for labels information.
```

Row positions, and data displaying might change.

2024-08-29 23:28 UTC, andrekomor commented on README.md
> +| 18 | [CMMD](https://www.cancerimagingarchive.net/collection/cmmd/) | MG | Classification |
```suggestion
| 18 | [CMMD](https://www.cancerimagingarchive.net/collection/cmmd/) | XRAY | Classification |
```

Mammography is x-ray I guess. Please confirm @A-Huli

2024-08-29 23:28 UTC, andrekomor commented on config/dataset_config.py
> +    phases={"0": "MG"},
```suggestion
    phases={"0": "XRAY"},
```

Verify with @A-Huli

2024-08-31 22:04 UTC, KacperRogala commented on pyproject.toml
openpyxl package is required. Labels are saved in .xlsx file. To read them in LabelExtractor class pandas.read_excel() is used. Lack of openpyxl package causes error in this method.

2024-09-02 20:09 UTC, KacperRogala commented on README.md
> +| 18 | [CMMD](https://www.cancerimagingarchive.net/collection/cmmd/) | MG | Classification |
After consultation with @A-Huli at today's meeting (02.09) it was decided to keep MG as the phase name, as the project does not yet have strict restrictions on the phase name ontology.

2024-09-02 20:11 UTC, KacperRogala commented on config/dataset_config.py
> +    phases={"0": "MG"},
Similarly as above, after consultation with @A-Huli it was decided to keep MG as the phase name.

2024-09-04 18:30 UTC, KacperRogala commented on src/pipelines/cmmd.py
> +        img_id_final = lvl_higher + "_" + img_id
I changed it according to the suggestion.

2024-09-04 18:31 UTC, KacperRogala commented on config/runner_config.py
> +from src.pipelines import (  # CmmdPipeline,
Imports got fixed.

2024-09-04 18:32 UTC, KacperRogala commented on README.md
> +  4. Download CMMD_clinicaldata_revision.xlsx from Data Access table (second row) for labels information.
I changed it according to the suggestion.

2024-09-05 17:21 UTC, andrekomor commented on pyproject.toml
Ok, closing

2024-09-05 18:13 UTC, andrekomor commented on config/runner_config.py
> +            source_path="",  # Path to 'manifest-1616439774456/CMMD' folder
```suggestion
            source_path="",  # Path to 'manifest-{xxxxxxxxxxxx}/CMMD' folder
```
I think manifest number is unique to single process of downloading via tcia, not connected to the dataset.

2024-09-05 18:26 UTC, andrekomor commented on config/runner_config.py
> +            source_path="",  # Path to 'manifest-1616439774456/CMMD' folder
Also please fix pre-commit fails. There are some empty spaces left at the end of some lines. You can run it locally using `pre-commit run --all-files`

2024-09-08 14:16 UTC, KacperRogala commented on config/runner_config.py
> +            source_path="",  # Path to 'manifest-1616439774456/CMMD' folder
Changes are made.

2024-09-08 14:21 UTC, KacperRogala commented on config/runner_config.py
> +            source_path="",  # Path to 'manifest-1616439774456/CMMD' folder
I also had to change the `source_path` in` testing/tests/test_cmmd.py` a bit to match the path in the test_dummy_data folder on google drive.

2024-09-09 18:52 UTC, andrekomor commented on testing/tests/test_cmmd.py
> +source_path = os.path.join(os.getcwd(), "testing/test_dummy_data/18_cmmd/input/manifest-1616439774456/CMMD")
I guess we could just leave it as it was. We are not really interested in manifest folder. we can have CMMD folder straight in input folder

2024-09-09 18:53 UTC, andrekomor approved these changes

2024-09-09 23:08 UTC, KacperRogala commented on testing/tests/test_cmmd.py
> +source_path = os.path.join(os.getcwd(), "testing/test_dummy_data/18_cmmd/input/manifest-1616439774456/CMMD")
I changed it back to "testing/test_dummy_data/18_cmmd/input/CMMD".

2024-09-10 06:28 UTC, andrekomor approved these changes

2024-09-10 17:31 UTC, andrekomor commented
Make sure testing step is passing before merging

2024-09-11 19:59 UTC, KacperRogala commented
> Make sure testing step is passing before merging

Honestly, I don't know why the test is failing. Based on the fail message, I understand that it can't find the `CMMD_clinicaldata_revision.xlsx` file. But it should be in the test files, at least it is on the drive.

2024-09-24 11:41 UTC, merged