Ct_org pipeline
TheLion-ai/UMIE_datasets pull request #94
Opened 2024-09-22 19:52 UTC by Piotr1219

Issue: https://github.com/TheLion-ai/UMIE_datasets/issues/4

- add CT_ORG pipeline 
- modify reading .nii files to not fail on corrupted files
- modify recolor_masks to be resistant to source and target colors from the same values range

2024-10-02 07:23 UTC, andrekomor requested changes
Make sure to update README file also

2024-10-02 07:23 UTC, andrekomor commented on src/constants.py
> +TARGET_PATH = "/Users/piotr/Desktop/UMIE/processed_data"  # name of the folder, where processed outputs will be placed
:)

2024-10-02 07:23 UTC, andrekomor commented on config/runner_config.py
> +            target_path=TARGET_PATH,
Same as in other pipelines
```suggestion
            target_path=TARGET_PATH,
            masks_path="",
```

2024-10-02 07:23 UTC, andrekomor commented on src/pipelines/ct_org.py
> +class CTORGPipeline(BasePipeline):
It is good practice to use abbreviations as other words for readability reasons (Only first letter large) [(Source)](https://www.approxion.com/capital-offenses-how-to-handle-abbreviations-in-camelcase/). Please change everywhere this is used.
![image](https://github.com/user-attachments/assets/48c38016-5a78-4d40-89de-66e3501bbe73)

```suggestion
class CtOrgPipeline(BasePipeline):
```

2024-10-02 07:23 UTC, andrekomor commented on testing/tests/test_check_ct_org.py
rename file to `test_ct_org.py`

2024-10-02 07:23 UTC, andrekomor commented on testing/tests/test_check_ct_org.py
> +test_coronahack.
Update

2024-10-02 07:23 UTC, andrekomor commented on testing/tests/test_check_ct_org.py
> +
Add initial clean_up step (It is implemented already in other test files)

2024-10-02 07:23 UTC, andrekomor commented on testing/tests/test_check_ct_org.py
> +
Add check jsonl step

2024-10-07 18:59 UTC, andrekomor approved these changes

2024-10-07 19:03 UTC, andrekomor requested changes

2024-10-07 19:03 UTC, andrekomor commented on testing/tests/test_ct_org.py
> +def test_chest_xray14_verify_jsonl_correct():
Incorrect name

2024-10-07 19:03 UTC, andrekomor commented on testing/libs/dataset_testing_lib.py
> +        print(files_to_erase)
Remove

2024-10-07 19:03 UTC, andrekomor commented on src/pipelines/ct_org.py
> +            img_id_extractor=ImgIdExtractor(),  #
Remove `#`

2024-11-11 22:51 UTC, A-Huli approved these changes

2024-11-14 20:17 UTC, merged